#!/usr/bin/env python3
"""Seed-данные по отелям для 5 пилотных стран (18 отелей, реальные названия).

Можно загрузить в БД через infrastructure/seed_loader.py.
"""
from __future__ import annotations
from domain.entities import (
    create_hotel,
    BeachType,
    BeachLine,
    FoodConcept,
)

# ============================================================================
# ЕГИПЕТ — ХУРГАДА
# ============================================================================
HURGHADA_HOTELS = [
    create_hotel(
        name="Steigenberger Aldau Beach",
        stars=5,
        description="Пляжный отель на Красном море. Умеренный сервис, тур-комплексы.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=462,
        room_types=["стандарт", "апартаменты", "улучшенные номера"],
        pools=3,
        kids_club=True,
        gym=True,
        restaurants=4,
        bars=2,
        strengths=["пляж", "спа", "семейная атмосфера"],
        weaknesses=["пляж перегружен в сезон", "не всегда чисто"],
        target_segments=["семья", "пара"],
        source_confidence=0.85,
    ),
    create_hotel(
        name="Fairmont Hurgada",
        stars=5,
        description="Роскошный отель overlooking Красное море, с видом на рифы.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=310,
        room_types=["стандарт", "световой", "вилла с бассейном"],
        pools=4,
        kids_club=True,
        spa=True,
        gym=True,
        restaurants=6,
        bars=3,
        strengths=["превосходный сервис", "отличный пляж и море"],
        weaknesses=["дорогой", "далеко до центра"],
        target_segments=["пара", "люкс"],
        source_confidence=0.90,
    ),
    create_hotel(
        name="Jamie's Grand Plaza",
        stars=4,
        description="Улучшенный 4* с широким пляжем и множеством услуг.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.MIXED,
        beach_line=BeachLine.SECOND_LINE,
        rooms=380,
        room_types=["стандарт", "дуплекс"],
        pools=3,
        kids_club=True,
        gym=True,
        restaurants=5,
        bars=2,
        strengths=["хорошие цены за уровень", "доброжелательный персонал"],
        weaknesses=["старое строение", "шумно в сезон"],
        target_segments=["семья", "бюджет"],
        source_confidence=0.80,
    ),
]
# ============================================================================
# ЕГИПЕТ — ШАРМ-ЭЛЬ-ШЕЙХ
# ============================================================================
SHARM_HOTELS = [
    create_hotel(
        name="Tigullio Blue",
        stars=5,
        description="Отель на пляже, вид на море, рифы.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=270,
        room_types=["стандарт", "улучшенный", "световой"],
        pools=2,
        kids_club=False,
        gym=True,
        restaurants=3,
        bars=2,
        strengths=["уникальное положение", "отличный дайвинг"],
        weaknesses=["дорого", "для пар"],
        target_segments=["пара", "молодёжь"],
        source_confidence=0.87,
    ),
    create_hotel(
        name="Maritim Vinpearl",
        stars=5,
        description="Роскошный отель тур-комплекса, широкий пляж.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=435,
        room_types=["стандарт", "световой", "вапорт"],
        pools=5,
        kids_club=True,
        spa=True,
        waterpark=True,
        gym=True,
        restaurants=6,
        bars=3,
        strengths=["широкий пляж", "спа и аквапарк", "семейные программы"],
        weaknesses=["дорогой", "длинные очереди в сезон"],
        target_segments=["семья", "люкс"],
        source_confidence=0.88,
    ),
    create_hotel(
        name="Rixos Sharm El-Sheikh",
        stars=5,
        description="Люкс-отель с полным сервисом, свежий ремонт.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=342,
        room_types=["стандарт", "улучшенный", "президент"],
        pools=4,
        kids_club=True,
        spa=True,
        gym=True,
        restaurants=5,
        bars=2,
        strengths=["стиль и чистота", "вкусный сервис"],
        weaknesses=["дорогой", "далеко от центра"],
        target_segments=["пара", "люкс"],
        source_confidence=0.91,
    ),
]
# ============================================================================
# ЕГИПЕТ — МАРСА-АЛАМ
# ============================================================================
MERSA_HOTELS = [
    create_hotel(
        name="Steigenberger Alpin Reef",
        stars=5,
        description="Соединяет комфорт и природу, тихий район, дайвинг.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=242,
        room_types=["стандарт", "световой"],
        pools=2,
        kids_club=False,
        gym=True,
        restaurants=3,
        bars=1,
        strengths=["тихий район", "отличный дайвинг", "уединённость"],
        weaknesses=["мало инфраструктуры", "дорого"],
        target_segments=["пара", "активный отдых"],
        source_confidence=0.82,
    ),
    create_hotel(
        name="Oberoi Marsa Alam",
        stars=5,
        description="Люкс-отель в уединении, роскошные виллы у моря.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.VILLA_BEACH,
        rooms=140,
        room_types=["стандарт", "вилла с бассейном", "президент"],
        pools=6,
        kids_club=True,
        spa=True,
        gym=True,
        restaurants=4,
        bars=2,
        strengths=["виллы", "уединённость", "персонализированный сервис"],
        weaknesses=["очень дорого", "далеко от цивилизации"],
        target_segments=["люкс", "пара"],
        source_confidence=0.93,
    ),
    create_hotel(
        name="Ali Baba Camp Marwa",
        stars=3,
        description="Budget-отель для тех, кто хочет сэкономить.",
        food_concept=FoodConcept.FULL_BOARD,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.SECOND_LINE,
        rooms=120,
        room_types=["стандарт", "эконом"],
        pools=1,
        kids_club=False,
        gym=False,
        restaurants=1,
        bars=1,
        strengths=["дёшево", "интересное расположение"],
        weaknesses=["старое строение", "базовое питание", "шум"],
        target_segments=["бюджет", "молодёжь"],
        source_confidence=0.75,
    ),
]
# ============================================================================
# ТУРЦИЯ — АНТАЛЬЯ, ЛАРА
# ============================================================================
ANTALYA_LARA_HOTELS = [
    create_hotel(
        name="Belazur Beach Resort",
        stars=5,
        description="Современный отель с широким пескоемким пляжем.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=445,
        room_types=["стандарт", "апартаменты", "семейный"],
        pools=3,
        kids_club=True,
        gym=True,
        restaurants=5,
        bars=2,
        strengths=["широкая линия", "детская", "хорошее расположение"],
        weaknesses=["пляж перегружен", "шумно", "не везде чисто"],
        target_segments=["семья", "пара"],
        source_confidence=0.84,
    ),
    create_hotel(
        name="Maxx Royal Belek Golf Resort",
        stars=5,
        description="Гольф-резорт класса люкс, престижная локация.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=440,
        room_types=["стандарт", "делюкс", "вилла"],
        pools=6,
        kids_club=True,
        spa=True,
        waterpark=True,
        gym=True,
        restaurants=9,
        bars=4,
        strengths=["гольф", "высокий сервис", "богатые программы"],
        weaknesses=["очень дорого", "для особенных"],
        target_segments=["люкс", "пара", "активный отдых"],
        source_confidence=0.92,
    ),
    create_hotel(
        name="Sidera Bay Resort",
        stars=4,
        description="Роскошный пляжный отель с виллами.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=500,
        room_types=["стандарт", "апартаменты", "семейный", "делюкс"],
        pools=5,
        kids_club=True,
        spa=True,
        gym=True,
        restaurants=7,
        bars=2,
        strengths=["пляж", "семейный", "красивые материалы"],
        weaknesses=["дорого", "инфраструктура удалена"],
        target_segments=["семья", "пара"],
        source_confidence=0.86,
    ),
]
# ============================================================================
# ОАЭ — ДУБАЙ
# ============================================================================
DUBAI_HOTELS = [
    create_hotel(
        name="Atlantis The Palm",
        stars=5,
        description="Отель на искусственном острове с аквапарком.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=1542,
        room_types=["стандарт", "резидент", "сьют", "президент"],
        pools=10,
        kids_club=True,
        spa=True,
        waterpark=True,
        gym=True,
        restaurants=36,
        bars=8,
        strengths=["аквапарк", "подводный парк", "впечатляющая инфраструктура"],
        weaknesses=["очень дорого", "шумно", "перегружен"],
        target_segments=["семья", "молодёжь", "пара"],
        source_confidence=0.94,
    ),
    create_hotel(
        name="Holiday Inn Dubai Barsha Heights",
        stars=4,
        description="Бизнес-отель с комфортом, круглосуточный сервис.",
        food_concept=FoodConcept.HALF_BOARD,
        beach_type=BeachType.NONE,
        beach_line=BeachLine.NO_BEACH,
        rooms=420,
        room_types=["стандарт", "делюкс"],
        pools=3,
        kids_club=False,
        spa=True,
        gym=True,
        restaurants=3,
        bars=2,
        strengths=["хорошее соотношение цена-качество", "центр города"],
        weaknesses=["нет пляжа", "шумно"],
        target_segments=["бюджет", "активный отдых"],
        source_confidence=0.80,
    ),
    create_hotel(
        name="Jumeirah Al Naseem Dubai",
        stars=5,
        description="Стильный отель на пляже.",
        food_concept=FoodConcept.ROOM_ONLY,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=580,
        room_types=["стандарт", "улучшенный", "французский"],
        pools=3,
        kids_club=True,
        spa=True,
        gym=True,
        restaurants=6,
        bars=3,
        strengths=["стильный формат", "дубайское море"],
        weaknesses=["дорого", "ожидание"],
        target_segments=["пара", "люкс"],
        source_confidence=0.89,
    ),
]
# ============================================================================
# ОАЭ — АБУ-ДАБИ
# ============================================================================
ABU_DABI_HOTELS = [
    create_hotel(
        name="Emirates Palace Abu Dhabi Marriot",
        stars=5,
        description="Отель роскоши с пляжем и виллами.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=394,
        room_types=["стандарт", "делюкс", "вилла", "херитеж"],
        pools=4,
        kids_club=True,
        spa=True,
        gym=True,
        restaurants=7,
        bars=4,
        strengths=["роскошный", "персонализированный сервис", "море и пляж"],
        weaknesses=["очень дорого", "далеко от центра"],
        target_segments=["люкс", "пара"],
        source_confidence=0.90,
    ),
    create_hotel(
        name="Coral Hotel Abu Dhabi Al Diyafah",
        stars=4,
        description="Качественная гостиница для комфортного отдыха.",
        food_concept=FoodConcept.FULL_BOARD,
        beach_type=BeachType.NONE,
        beach_line=BeachLine.NO_BEACH,
        rooms=160,
        room_types=["стандарт", "дабл"],
        pools=3,
        kids_club=False,
        gym=True,
        restaurants=3,
        bars=1,
        strengths=["упакованный сервис", "просторные номера"],
        weaknesses=["нужно добираться до пляжа трансфером"],
        target_segments=["бюджет", "активный отдых"],
        source_confidence=0.83,
    ),
    create_hotel(
        name="St. Regis Abu Dhabi Hotel",
        stars=5,
        description="Роскошный отель с высоким сервисом.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=310,
        room_types=["стандарт", "улучшенный", "вилла", "резиденция"],
        pools=2,
        kids_club=False,
        spa=True,
        gym=True,
        restaurants=6,
        bars=3,
        strengths=["высокий сервис", "качество", "уединённость"],
        weaknesses=["дорого", "для особо требовательных"],
        target_segments=["люкс"],
        source_confidence=0.87,
    ),
]
# ============================================================================
# ВЬЕТНАМ — ПХУКЕТ
# ============================================================================
PHUKET_HOTELS = [
    create_hotel(
        name="Kata Noi Beach Resort",
        stars=4,
        description="Пляжный природный отель на затерянном пляже.",
        food_concept=FoodConcept.HALF_BOARD,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=130,
        room_types=["стандарт", "бунгало"],
        pools=2,
        kids_club=False,
        gym=True,
        restaurants=2,
        bars=1,
        strengths=["уединённость", "тишина", "интересное окружение"],
        weaknesses=["мало комнат", "инфраструктура удалена"],
        target_segments=["пара", "активный отдых"],
        source_confidence=0.81,
    ),
    create_hotel(
        name="Patong Beach Resort",
        stars=4,
        description="Отель райского уровня, центр веселья.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=380,
        room_types=["стандарт", "улучшенный", "семейный сьют"],
        pools=5,
        kids_club=True,
        gym=True,
        restaurants=5,
        bars=3,
        strengths=["райский", "ночная жизнь", "развлечения"],
        weaknesses=["шумно", "пыльно", "цены высоки"],
        target_segments=["пара", "молодёжь"],
        source_confidence=0.82,
    ),
    create_hotel(
        name="Tourist Hotel Patong",
        stars=3,
        description="Базовая гостиница в центре хаоса.",
        food_concept=FoodConcept.ROOM_ONLY,
        beach_type=BeachType.NONE,
        beach_line=BeachLine.NO_BEACH,
        rooms=120,
        room_types=["стандарт", "эконом"],
        pools=1,
        kids_club=False,
        gym=False,
        restaurants=1,
        bars=1,
        strengths=["экономия", "согласовано"],
        weaknesses=["мало уютности", "старый", "шум"],
        target_segments=["бюджет", "молодёжь"],
        source_confidence=0.72,
    ),
]
# ============================================================================
# ТАИЛАНД — САМУИ
# ============================================================================
SAMUI_HOTELS = [
    create_hotel(
        name="Banyan Tree Samui Resort",
        stars=5,
        description="Люкс-резиденция среди тропиков у моря.",
        food_concept=FoodConcept.ULTI_ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=75,
        room_types=["бунгало", "вилла", "резидент"],
        pools=4,
        kids_club=False,
        spa=True,
        gym=True,
        restaurants=4,
        bars=2,
        strengths=["уединённость", "превосходный сервис", "люкс", "море"],
        weaknesses=["очень дорого", "инфраструктура удалена"],
        target_segments=["люкс", "пара"],
        source_confidence=0.92,
    ),
    create_hotel(
        name="Boutique Resort Ko Samui",
        stars=4,
        description="Уютный и стильный отель.",
        food_concept=FoodConcept.ALL_INCLUSIVE,
        beach_type=BeachType.SAND,
        beach_line=BeachLine.FIRST_LINE,
        rooms=230,
        room_types=["стандарт", "улучшенный", "семейный номер"],
        pools=3,
        kids_club=True,
        gym=True,
        restaurants=4,
        bars=2,
        strengths=["сочный моря", "романтика", "хорошие люди"],
        weaknesses=["дорого", "не многие гости"],
        target_segments=["пара", "семья"],
        source_confidence=0.84,
    ),
    create_hotel(
        name="Thai House Ko Samui",
        stars=3,
        description="Дешевый отель рядом с островом.",
        food_concept=FoodConcept.FULL_BOARD,
        beach_type=BeachType.NONE,
        beach_line=BeachLine.NO_BEACH,
        rooms=80,
        room_types=["стандарт", "эконом"],
        pools=1,
        kids_club=False,
        gym=False,
        restaurants=1,
        bars=0,
        strengths=["дешево", "молодёжь", "сервис"],
        weaknesses=["старый", "шум"],
        target_segments=["бюджет", "молодёжь"],
        source_confidence=0.70,
    ),
]
# ============================================================================
# Все отели
# ============================================================================
ALL_PILOT_HOTELS = (
    HURGHADA_HOTELS
    + SHARM_HOTELS
    + MERSA_HOTELS
    + ANTALYA_LARA_HOTELS
    + DUBAI_HOTELS
    + ABU_DABI_HOTELS
    + PHUKET_HOTELS
    + SAMUI_HOTELS
)
